dist: trusty
sudo: false

language: node_js
node_js:
  - '10.15.3'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env : "authenticatin"
  bucket_name: "elasticbeanstalk-us-east-2-616335513978"
  bucket_path: "s3://elasticbeanstalk-us-east-2-616335513978/docker/travis-a14bcce6747ac78792b4c633f2441736be37cfa1-1563224001.zip"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
