sudo: required
services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - docker build -t image -f Dockerfile.dev .


install:
  - npm install


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env : "authenticatin"
  bucket_name: "elasticbeanstalk-us-east-2-616335513978"
  bucket_path: "s3://elasticbeanstalk-us-east-2-616335513978/docker/travis-a14bcce6747ac78792b4c633f2441736be37cfa1-1563224001.zip"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
